### ISSUE TITLE
Q for Permission 

### ISSUE THREAD

**Issue by eveJiang** [snauhaus/link_compustat_ibes#2]
Hi, when I run code "db.get_table(library='ibes', table='idsum', columns=['ticker', 'cusip', 'cname']) " I got a Programming error:

ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied for schema tr_ibes

[SQL: SELECT ticker,cusip,cname FROM ibes.idsum  OFFSET 0;]
(Background on this error at: http://sqlalche.me/e/f405)

Does it mean I don't have access to use this I/B/E/S database? 
Thanks~

**Comment by snauhaus** [comment]
Hi, if so, then it’s not an issue with the script. Maybe get in touch with wrds?
